a_sabr: "../host.rc"

peer_list:
  - uuid: "1"
    name: Instance 1
    endpoints:
      - type: TCP
        address: 127.0.0.1:6500
      - type: UDP
        address: 127.0.0.1:6550
    color: 0
    
  - uuid: "2"
    name: Instance 2
    endpoints:
      - type: TCP
        address: 127.0.0.1:7500
      - type: UDP
        address: 127.0.0.1:7550
    color: 1
  - uuid: "3"
    name: Instance 3
    endpoints:
      - type: TCP
        address: 127.0.0.1:8000
      - type: UDP
        address: 127.0.0.1:8050
    color: 2
    
room_list:
  - uuid: 1
    name: Default
    participants:
      - Instance 1
      - Instance 2
      - Instance 3
